import { useApp } from '../context/AppContext';
import MetricCard from '../components/MetricCard';
import BarChart from '../components/BarChart';

export default function Dashboard() {
  const { t, certificates, accounts, incomes, expenses } = useApp();

  const certsMonth = certificates.filter(c => c.issue_date.startsWith('2026-07')).length;
  const totalBalance = Object.values(accounts).reduce((a, b) => a + b, 0);
  const pendingPayments = certificates.filter(c => c.status === 'submitted').length;
  const netBalance = incomes.reduce((a, b) => a + b.amount, 0) - expenses.reduce((a, b) => a + b.amount, 0);

  const months = ['Feb','Mar','Apr','May','Jun','Jul'];
  const certsIssued = [34,41,38,47,52,58];
  const certBars = months.map((m, i) => ({ label: m, value: certsIssued[i] }));

  return (
    <div className="max-w-6xl">
      <div className="grid grid-cols-2 lg:grid-cols-5 gap-4 mb-6">
        <MetricCard label={t.dashboard + ' — Certs (mo)'} value={certsMonth} variant="primary" />
        <MetricCard label="Total Account Balance" value={`$${totalBalance.toLocaleString()}`} />
        <MetricCard label="Verified Payments" value={incomes.filter(i => i.autoGenerated).length} />
        <MetricCard label="Pending Payments" value={pendingPayments} variant="warning" />
        <MetricCard label="Net Balance" value={`$${netBalance.toLocaleString()}`} />
      </div>
      <div className="grid lg:grid-cols-2 gap-4 mb-6">
        <div className="bg-white border border-slate-200 rounded-xl p-5">
          <h3 className="text-sm font-bold mb-4">Certificates Issued (last 6 months)</h3>
          <BarChart data={certBars} />
        </div>
        <div className="bg-white border border-slate-200 rounded-xl p-5">
          <h3 className="text-sm font-bold mb-4">Account Balances</h3>
          <div className="space-y-2.5">
            {Object.entries(accounts).map(([name, balance]) => (
              <div key={name} className="flex justify-between text-sm border-b border-slate-100 pb-2 last:border-0">
                <span className="text-slate-600 font-medium">{name}</span>
                <span className="font-bold">${balance.toLocaleString()}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
