import { useApp } from '../context/AppContext';
import MetricCard from '../components/MetricCard';
import BarChart from '../components/BarChart';

export default function Observer() {
  const { certificates, accounts, incomes } = useApp();
  const certsMonth = certificates.filter(c => c.issue_date.startsWith('2026-07')).length;
  const totalBalance = Object.values(accounts).reduce((a, b) => a + b, 0);
  const months = ['Feb','Mar','Apr','May','Jun','Jul'];
  const certsIssued = [34,41,38,47,52,58];
  const certBars = months.map((m, i) => ({ label: m, value: certsIssued[i] }));

  return (
    <div className="max-w-6xl">
      <p className="text-sm text-slate-500 mb-6">View-only access: issued certificate counts and the payment dashboard.</p>
      <div className="grid grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
        <MetricCard label="Certificates Issued (mo)" value={certsMonth} variant="primary" />
        <MetricCard label="Total Account Balance" value={`$${totalBalance.toLocaleString()}`} />
        <MetricCard label="Verified Payments" value={incomes.filter(i => i.autoGenerated).length} />
      </div>
      <div className="bg-white border border-slate-200 rounded-xl p-5">
        <h3 className="text-sm font-bold mb-4">Certificates Issued (last 6 months)</h3>
        <BarChart data={certBars} />
      </div>
    </div>
  );
}
