import React, { createContext, useContext, useState, useMemo } from 'react';
import {
  Certificate, Payment, IncomeExpense, ExporterEntity, ImporterEntity, UserEntity, Role, AccountName, AnimalRow
} from '../types';
import {
  initialCertificates, initialPayments, initialIncomes, initialExpenses, initialAccounts,
  initialExporters, initialImporters, initialUsers, speciesRateDefaults,
} from '../data/mockData';
import { translations, Lang } from '../i18n/translations';

interface AppState {
  lang: Lang; setLang: (l: Lang) => void; toggleLang: () => void;
  t: typeof translations[Lang];
  currentRole: Role; setCurrentRole: (r: Role) => void;
  certificates: Certificate[];
  addCertificate: (c: Certificate) => void;
  updateCertificateStatus: (id: number, status: Certificate['status']) => void;
  payments: Payment[];
  accounts: Record<AccountName, number>;
  incomes: IncomeExpense[]; expenses: IncomeExpense[];
  addIncome: (i: IncomeExpense) => void; addExpense: (e: IncomeExpense) => void;
  exporters: ExporterEntity[]; importers: ImporterEntity[]; users: UserEntity[];
  verifyPayment: (cert: Certificate, account: AccountName) => void;
  speciesRates: Record<string, number>;
  auditLog: { id: number; text: string; date: string }[];
}

const AppContext = createContext<AppState | null>(null);

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');
  const [currentRole, setCurrentRole] = useState<Role>('Admin');
  const [certificates, setCertificates] = useState<Certificate[]>(initialCertificates);
  const [payments] = useState<Payment[]>(initialPayments);
  const [accounts, setAccounts] = useState(initialAccounts);
  const [incomes, setIncomes] = useState<IncomeExpense[]>(initialIncomes);
  const [expenses, setExpenses] = useState<IncomeExpense[]>(initialExpenses);
  const [auditLog, setAuditLog] = useState<{ id: number; text: string; date: string }[]>([]);

  const t = translations[lang];

  const addCertificate = (c: Certificate) => setCertificates(prev => [c, ...prev]);
  const updateCertificateStatus = (id: number, status: Certificate['status']) =>
    setCertificates(prev => prev.map(c => c.id === id ? { ...c, status } : c));

  const addIncome = (i: IncomeExpense) => {
    setIncomes(prev => [i, ...prev]);
    if (i.account) setAccounts(prev => ({ ...prev, [i.account as AccountName]: prev[i.account as AccountName] + i.amount }));
  };
  const addExpense = (e: IncomeExpense) => {
    setExpenses(prev => [e, ...prev]);
    if (e.account) setAccounts(prev => ({ ...prev, [e.account as AccountName]: prev[e.account as AccountName] - e.amount }));
  };

  const verifyPayment = (cert: Certificate, account: AccountName) => {
    updateCertificateStatus(cert.id, 'payment_approved');
    const amount = cert.feeAmount || 0;
    addIncome({ id: Date.now(), category: 'Certificate Fee', amount, description: `${cert.certificate_number} payment`, date: new Date().toISOString().slice(0,10), account, autoGenerated: true });
    setAuditLog(prev => [{ id: Date.now(), text: `Payment verified for ${cert.certificate_number} — $${amount} into ${account}`, date: new Date().toISOString() }, ...prev]);
  };

  const value = useMemo<AppState>(() => ({
    lang, setLang, toggleLang: () => setLang(l => l === 'en' ? 'ar' : 'en'), t,
    currentRole, setCurrentRole,
    certificates, addCertificate, updateCertificateStatus,
    payments, accounts, incomes, expenses, addIncome, addExpense,
    exporters: initialExporters, importers: initialImporters, users: initialUsers,
    verifyPayment, speciesRates: speciesRateDefaults, auditLog,
  }), [lang, currentRole, certificates, payments, accounts, incomes, expenses, auditLog]);

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within AppProvider');
  return ctx;
}

export function emptyAnimalRow(): AnimalRow {
  return { species: '', breed: '', sex: '', age: '', earTag: '', quantity: '' };
}
