export type Role = 'Admin' | 'Veterinary Officer' | 'Data Entry Clerk' | 'Finance Officer' | 'Data Field Collector' | 'Observer';

export type CertStatus = 'draft' | 'submitted' | 'payment_approved' | 'approved' | 'printed' | 'cancelled';

export interface AnimalRow {
  species: string;
  breed?: string;
  sex?: string;
  age?: string;
  earTag?: string;
  quantity: string;
  rate?: string;
}

export interface Certificate {
  id: number;
  certificate_number: string;
  exporter: string;
  importer: string;
  country: string;
  port?: string;
  transport?: string;
  loadingPlace?: string;
  animals: string;
  animalRows?: AnimalRow[];
  status: CertStatus;
  issue_date: string;
  officer: string;
  breed?: string;
  sex?: string;
  age?: string;
  earTag?: string;
  quarantineDays?: string;
  quarantinePlace?: string;
  rvf?: string;
  fmd?: string;
  brucella?: string;
  testType?: string;
  vaccination?: string;
  clinicalExam?: string;
  remarks?: string;
  feeAmount?: number;
  voucherFileName?: string;
  voucherDataUrl?: string;
  approvedBy?: string;
  approvalDate?: string;
}

export interface Payment {
  id: number;
  certificate_number: string;
  customer: string;
  amount: number;
  method: string;
  status: 'pending' | 'completed' | 'refund';
  date: string;
}

export interface IncomeExpense {
  id: number;
  category: string;
  amount: number;
  description: string;
  date: string;
  account?: string;
  autoGenerated?: boolean;
}

export interface ExporterEntity { id: number; name: string; contact: string; phone: string; license: string; }
export interface ImporterEntity { id: number; name: string; country: string; contact: string; phone: string; }
export interface UserEntity { id: number; name: string; email: string; role: Role; status: 'active' | 'inactive'; }

export type AccountName = 'Cash' | 'Bank' | 'ZAAD' | 'EVC Plus' | 'Premier Wallet';
