import { Certificate, Payment, IncomeExpense, ExporterEntity, ImporterEntity, UserEntity, AccountName } from '../types';

export const initialCertificates: Certificate[] = [
  { id:1, certificate_number:'LCS-2026-0142', exporter:'Horn Exports Co.', importer:'Al Rajhi Trading (Saudi Arabia)', country:'Saudi Arabia', animals:'Sheep ×450', status:'approved', issue_date:'2026-07-30', officer:'Dr. Ahmed Nur', feeAmount: 1400 },
  { id:2, certificate_number:'LCS-2026-0141', exporter:'Al-Amin Livestock Trading', importer:'Gulf Livestock Imports (UAE)', country:'UAE', animals:'Cattle ×120', status:'printed', issue_date:'2026-07-28', officer:'Dr. Ahmed Nur', feeAmount: 860 },
  { id:3, certificate_number:'LCS-2026-0140', exporter:'Berbera Livestock Ltd', importer:'Jeddah Animal Market', country:'Saudi Arabia', animals:'Goat ×300', status:'draft', issue_date:'2026-07-31', officer:'Dr. Ahmed Nur', feeAmount: 1100 },
  { id:4, certificate_number:'LCS-2026-0139', exporter:'Golden Gate Traders', importer:'Al Rajhi Trading (Saudi Arabia)', country:'Saudi Arabia', animals:'Camel ×40', status:'printed', issue_date:'2026-07-20', officer:'Dr. Ahmed Nur', feeAmount: 700 },
  { id:5, certificate_number:'LCS-2026-0138', exporter:'Horn Exports Co.', importer:'Gulf Livestock Imports (UAE)', country:'UAE', animals:'Sheep ×620', status:'approved', issue_date:'2026-07-25', officer:'Dr. Ahmed Nur', feeAmount: 1740 },
  { id:6, certificate_number:'LCS-2026-0137', exporter:'Al-Amin Livestock Trading', importer:'Jeddah Animal Market', country:'Saudi Arabia', animals:'Cattle ×85', status:'cancelled', issue_date:'2026-07-15', officer:'Dr. Ahmed Nur', feeAmount: 610 },
  { id:7, certificate_number:'LCS-2026-0136', exporter:'Berbera Livestock Ltd', importer:'Al Rajhi Trading (Saudi Arabia)', country:'Saudi Arabia', animals:'Goat ×410', status:'printed', issue_date:'2026-07-12', officer:'Dr. Ahmed Nur', feeAmount: 1320 },
  { id:8, certificate_number:'LCS-2026-0135', exporter:'Horn Exports Co.', importer:'Gulf Livestock Imports (UAE)', country:'UAE', animals:'Sheep ×390', status:'printed', issue_date:'2026-07-10', officer:'Dr. Ahmed Nur', feeAmount: 1180 },
  { id:9, certificate_number:'LCS-2026-0134', exporter:'Golden Gate Traders', importer:'Jeddah Animal Market', country:'Saudi Arabia', animals:'Cattle ×60', status:'draft', issue_date:'2026-07-05', officer:'Dr. Ahmed Nur', feeAmount: 480 },
];

export const initialPayments: Payment[] = [
  { id:1, certificate_number:'LCS-2026-0142', customer:'Horn Exports Co.', amount:1400, method:'Bank', status:'completed', date:'2026-07-30' },
  { id:2, certificate_number:'LCS-2026-0140', customer:'Berbera Livestock Ltd', amount:1100, method:'ZAAD', status:'pending', date:'2026-07-31' },
  { id:3, certificate_number:'LCS-2026-0138', customer:'Horn Exports Co.', amount:1740, method:'Cash', status:'completed', date:'2026-07-25' },
];

export const initialIncomes: IncomeExpense[] = [
  { id:1, category:'Certificate Fee', amount:1400, description:'LCS-2026-0142 payment', date:'2026-07-30', account:'Bank', autoGenerated:true },
  { id:2, category:'Certificate Fee', amount:1740, description:'LCS-2026-0138 payment', date:'2026-07-25', account:'Cash', autoGenerated:true },
  { id:3, category:'Inspection Fee', amount:300, description:'Additional inspection charge', date:'2026-07-20' },
];

export const initialExpenses: IncomeExpense[] = [
  { id:1, category:'Office Rent', amount:800, description:'July office rent', date:'2026-07-01', account:'Bank' },
  { id:2, category:'Fuel', amount:150, description:'Field vehicle fuel', date:'2026-07-15', account:'Cash' },
];

export const initialAccounts: Record<AccountName, number> = {
  Cash: 4200, Bank: 18600, ZAAD: 2100, 'EVC Plus': 1500, 'Premier Wallet': 900,
};

export const initialExporters: ExporterEntity[] = [
  { id:1, name:'Horn Exports Co.', contact:'Ahmed Yusuf', phone:'+252 61 234 5678', license:'EXP-2201' },
  { id:2, name:'Al-Amin Livestock Trading', contact:'Fatima Warsame', phone:'+252 61 987 6543', license:'EXP-2202' },
  { id:3, name:'Berbera Livestock Ltd', contact:'Omar Ali', phone:'+252 61 555 1122', license:'EXP-2203' },
  { id:4, name:'Golden Gate Traders', contact:'Layla Hassan', phone:'+252 61 444 3399', license:'EXP-2204' },
];

export const initialImporters: ImporterEntity[] = [
  { id:1, name:'Al Rajhi Trading (Saudi Arabia)', country:'Saudi Arabia', contact:'Khalid Al Rajhi', phone:'+966 50 123 4567' },
  { id:2, name:'Gulf Livestock Imports (UAE)', country:'UAE', contact:'Rashid Al Maktoum', phone:'+971 50 987 6543' },
  { id:3, name:'Jeddah Animal Market', country:'Saudi Arabia', contact:'Sami Zahrani', phone:'+966 55 222 3344' },
];

export const initialUsers: UserEntity[] = [
  { id:1, name:'Dr. Ahmed Nur', email:'ahmed.nur@livestockgate.gov', role:'Admin', status:'active' },
  { id:2, name:'Dr. Sara Hassan', email:'sara.hassan@livestockgate.gov', role:'Veterinary Officer', status:'active' },
  { id:3, name:'Mo Farah', email:'mo.farah@livestockgate.gov', role:'Data Entry Clerk', status:'active' },
  { id:4, name:'Amina Jama', email:'amina.jama@livestockgate.gov', role:'Finance Officer', status:'active' },
  { id:5, name:'Yusuf Abdi', email:'yusuf.abdi@livestockgate.gov', role:'Data Field Collector', status:'active' },
];

export const speciesRateDefaults: Record<string, number> = { Cattle: 3, Sheep: 2, Goat: 2, Camel: 5 };
